### ISSUE TITLE
Issue with DiffEqBase in LorenzParameter Estimation

### ISSUE THREAD

**Issue by finmod** [JuliaDiffEq/DiffEqBenchmarks.jl#13]
Thanks for all the recent tremendous improvments in all directions. 
Trying to run the LorenzParameterEstimation notebook, after Pkg.update(), I get: 

At 
g1 = @ode_def LorenzExample begin
  dx = σ*(y-x)
  dy = x*(ρ-z) - y
  dz = x*y - β*z
end σ ρ β   
p = [10.0,28.0,2.66] 
r0 = [1.0; 0.0; 0.0]   
tspan = (0.0, 30.0)   
prob = ODEProblem(g1, r0, tspan,p)
tspan2 = (0.0, 3.0)   
prob_short = ODEProblem(g1, r0, tspan2,p)

I get the following error:

MethodError: no method matching DiffEqBase.ODEProblem(::LorenzExample, ::Array{Float64,1}, ::Tuple{Float64,Float64}, ::Array{Float64,1})
Closest candidates are:
  DiffEqBase.ODEProblem(::Any, ::Any, ::Any; kwargs...) at C:\Users\Denis\.julia\v0.6\DiffEqBase\src\problems/ode_problems.jl:26

Stacktrace:
 [1] include_string(::String, ::String) at .\loading.jl:522

**Comment by ChrisRackauckas** [comment]
It looks like you don't have the latest DiffEqBase. What does `Pkg.status("DiffEqBase")` say?

**Comment by finmod** [comment]
DiffEqBase 2.10.2. Also which DiffEqBayes to install?

**Comment by ChrisRackauckas** [comment]
If you click on the releases page of the Github package it'll note what the latest release is. It's the button with the little tag icon at the above the source code.

https://github.com/JuliaDiffEq/DiffEqBase.jl/releases

`v3.0.4` for DiffEqBase. You need >3 for the syntax change. DiffEqBayes

https://github.com/JuliaDiffEq/DiffEqBayes.jl/releases

should be v0.1.0. If you have master on any of the previous versions it won't allow you to update (it was created so that way no one would get the updates until the full change went through, but now it will hold you back if you're holding any piece back).

**Comment by finmod** [comment]
Here is my Pkg.status(). It is not immediately obvious to me which master is creating the problem.

julia> Pkg.status()
19 required packages:
 - BlackBoxOptim                 0.3.0
 - BlackBoxOptimizationBenchmarking 0.0.1
 - DifferentialEquations         3.1.0
 - DynamicalSystems              0.9.0
 - Evolutionary                  0.1.2+             master
 - ExcelReaders                  0.8.2
 - GR                            0.25.0+            master
 - Gtk                           0.13.1
 - IJulia                        1.6.2
 - Juno                          0.4.0
 - LeastSquaresOptim             0.4.0
 - MCMCDiagnostics               0.1.0+             master
 - MultivariateStats             0.4.0
 - NLopt                         0.3.6
 - PGFPlots                      2.2.1
 - Plots                         0.15.0
 - PyCall                        1.15.0
 - PyPlot                        2.3.2
 - Turing                        0.4.0+             master
173 additional packages:
 - AbstractFFTs                  0.2.1
 - AlgebraicDiffEq               0.1.0
 - ArgCheck                      0.4.2
 - AutoHashEquals                0.2.0
 - AxisAlgorithms                0.2.0
 - AxisArrays                    0.2.0
 - BandedMatrices                0.3.1
 - BinDeps                       0.8.6
 - BinaryProvider                0.1.3
 - BoundaryValueDiffEq           0.3.0
 - BufferedStreams               0.3.3
 - CPUTime                       0.0.5
 - Cairo                         0.4.0
 - Calculus                      0.2.2
 - CatIndices                    0.1.0
 - ChaosTools                    0.4.3
 - ChunkedArrays                 0.1.1
 - CodecZlib                     0.4.2
 - ColorBrewer                   0.3.1
 - ColorTypes                    0.6.6
 - ColorVectorSpace              0.5.2
 - Colors                        0.8.2
 - Combinatorics                 0.5.0
 - CommonSubexpressions          0.0.1
 - Compat                        0.49.0
 - Compose                       0.5.4
 - ComputationalResources        0.2.0
 - Conda                         0.7.1
 - ContinuousTransformations     0.0.0-             master (unregistered)
 - Contour                       0.4.0
 - CoordinateTransformations     0.4.1
 - CoupledFields                 0.0.1
 - CustomUnitRanges              0.1.0
 - DataArrays                    0.6.2
 - DataFrames                    0.10.1
 - DataStructures                0.7.4
 - DelayDiffEq                   1.12.0
 - DiffBase                      0.3.2
 - DiffEqBase                    2.10.2
 - DiffEqBiological              0.3.0
 - DiffEqCallbacks               0.8.0
 - DiffEqDevTools                0.11.3
 - DiffEqDiffTools               0.2.1
 - DiffEqFinancial               0.3.0
 - DiffEqJump                    0.7.0
 - DiffEqMonteCarlo              0.9.1
 - DiffEqNoiseProcess            0.8.1
 - DiffEqPDEBase                 0.3.5
 - DiffEqParamEstim              0.8.0
 - DiffEqPhysics                 0.3.0
 - DiffEqSensitivity             0.5.1
 - DiffEqUncertainty             0.1.0
 - DiffResults                   0.0.3
 - DiffRules                     0.0.3
 - DiffWrappers                  0.0.0-             master (unregistered)
 - DimensionalPlotRecipes        0.0.2
 - Discretizers                  2.1.0
 - Distances                     0.5.0
 - DistributedArrays             0.4.0
 - Distributions                 0.15.0
 - DocStringExtensions           0.4.3
 - Documenter                    0.13.1
 - DualNumbers                   0.3.0
 - DynamicHMC                    0.0.0-             master (unregistered)
 - DynamicalSystemsBase          0.4.1
 - EllipsisNotation              0.3.0
 - FFTViews                      0.1.0
 - FFTW                          0.0.4
 - FileIO                        0.6.1
 - FiniteElementDiffEq           0.4.0
 - FixedPointNumbers             0.4.3
 - ForwardDiff                   0.7.2
 - FunctionWrappers              0.1.0
 - GZip                          0.3.0
 - Gadfly                        0.6.4
 - GenericSVD                    0.1.0
 - Graphics                      0.2.0
 - Hexagons                      0.1.0
 - IdentityRanges                0.1.0
 - ImageAxes                     0.4.0
 - ImageCore                     0.5.0
 - ImageFiltering                0.2.3
 - ImageMagick                   0.5.0
 - ImageMetadata                 0.4.0
 - ImageMorphology               0.0.2
 - ImageTransformations          0.4.1
 - Images                        0.12.0
 - IndirectArrays                0.3.0
 - Interpolations                0.7.3
 - IntervalSets                  0.1.1
 - IterTools                     0.2.1
 - IterativeSolvers              0.5.0
 - JSON                          0.16.4
 - KernelDensity                 0.4.0
 - LaTeXStrings                  0.3.0
 - Lazy                          0.12.0
 - LearnBase                     0.1.6
 - LibExpat                      0.4.1
 - Libz                          0.2.4
 - LightGraphs                   0.11.1
 - LineSearches                  3.2.5
 - LinearMaps                    1.0.4
 - Loess                         0.3.0
 - LossFunctions                 0.2.0
 - LsqFit                        0.3.0
 - MacroTools                    0.4.0
 - Mamba                         0.11.1
 - MappedArrays                  0.0.7
 - MathProgBase                  0.7.0
 - MbedTLS                       0.5.5
 - Measures                      0.1.0
 - Media                         0.3.0
 - Memoize                       0.2.0
 - Missings                      0.2.5
 - MuladdMacro                   0.0.2
 - MultiScaleArrays              0.6.0
 - NLSolversBase                 3.1.0
 - NLsolve                       0.13.0
 - NaNMath                       0.3.0
 - NearestNeighbors              0.3.0
 - Nullables                     0.0.3
 - OffsetArrays                  0.4.2
 - Optim                         0.11.0
 - OptimBase                     1.0.0
 - OrdinaryDiffEq                2.37.0
 - PDMats                        0.8.0
 - PaddedViews                   0.2.0
 - ParameterizedFunctions        3.0.0
 - Parameters                    0.8.1
 - PenaltyFunctions              0.0.2
 - PlotThemes                    0.2.0
 - PlotUtils                     0.4.4
 - Polynomials                   0.2.1
 - PositiveFactorizations        0.1.0
 - Primes                        0.2.0
 - ProgressMeter                 0.5.3
 - QuadGK                        0.2.0
 - RandomNumbers                 0.1.1
 - RangeArrays                   0.2.0
 - Ratios                        0.2.0
 - RecipesBase                   0.2.3
 - RecursiveArrayTools           0.14.5
 - Reexport                      0.1.0
 - Requires                      0.4.3
 - ResettableStacks              0.3.1
 - Rmath                         0.3.2
 - Roots                         0.5.0
 - Rotations                     0.6.1
 - SHA                           0.5.6
 - SIUnits                       0.1.0
 - ShowItLikeYouBuildIt          0.2.0
 - Showoff                       0.1.1
 - SimpleTraits                  0.5.1
 - SortingAlgorithms             0.2.0
 - SpecialFunctions              0.3.8
 - Stan                          2.0.2
 - StaticArrays                  0.6.6
 - StatsBase                     0.19.5
 - StatsFuns                     0.5.0
 - SteadyStateDiffEq             0.1.0
 - StochasticDiffEq              2.23.4
 - Sundials                      1.1.0
 - SymEngine                     0.3.0
 - TexExtensions                 0.1.0
 - TikzPictures                  1.2.0
 - TiledIteration                0.1.0
 - TranscodingStreams            0.4.1
 - URIParser                     0.3.0
 - Unrolled                      0.0.1
 - VectorizedRoutines            0.0.2
 - WinRPM                        0.3.1
 - WoodburyMatrices              0.2.2
 - ZMQ                           0.5.1

julia>

**Comment by ChrisRackauckas** [comment]
When did you last try updating? The dynamical systems packages would've held back DiffEq until last night.

**Comment by finmod** [comment]
I do Pkg.update() everytime I start a new Julia session including today pm GMT.

**Comment by ChrisRackauckas** [comment]
Hmm, it may just be easiest to discard your `.julia/v0.6` and start fresh... there's about 50 packages with the upper bound so finding out what caused it is very difficult, but adding things as you need them one-by-one makes it easy. 

My guess is that the problem is indirect. NLsolve and Optim did a change at the same time, and DiffEq now uses the newer syntax for them. But not all (most) packages haven't updated to the new NLsolve or Optim yet, so those will upper bound and push NLsolve/Optim back, which will push DiffEq back. The good news is that pretty much all of the widely used packages have updated that. The bad news is there's quite a few random things which haven't, and the authors are unresponsive...

**Comment by finmod** [comment]
Thanks. Will implement the radical solution.

**Comment by finmod** [comment]
The nuclear solution works perfectly. You can close this issue.
