### ISSUE TITLE
Benchmarks for ExpRK methods

### ISSUE THREAD

**Issue by MSeeker1340** [JuliaDiffEq/DiffEqBenchmarks.jl#30]
We should add one or two typical ExpRK methods to the stiff ODE benchmarks, and then do a separate one that benchmarks the impact of parameters specific to Krylov methods (e.g. Krylov dimension size and IOP).

**Comment by ChrisRackauckas** [comment]
I think HochOst4, EPIRK5P1, and EXPRB53s3 are probably the ones to do? And at low order, `ETDRK2`?

**Comment by ChrisRackauckas** [comment]
They have been added. They don't always do well (they need something like a PDE), but that's not something we can work on! Thanks for all of your hard work @MSeeker1340
