### ISSUE TITLE
Jump equations need to run

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBenchmarks.jl#43]
I'm not sure if they are fully updated or not. @isaacsas help? :)

**Comment by isaacsas** [comment]
Thanks for the reminder. I’ve got several of them locally converted, but it was a while ago. I’ll try to finish updating them and merge back in now that the Weave branch is the default. I’m hopefully done traveling for a bit so should have some time to work on this soon.
