### ISSUE TITLE
BCR import location

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBenchmarks.jl#55]
@isaacsas we need to find out how to make the import command computer-independent.

http://benchmarks.juliadiffeq.org/html/StiffODE/BCR.html

```julia
prnbng = loadrxnetwork(BNGNetwork(), "BNGRepressilator",
                       joinpath(pathof(ReactionNetworkImporters),"..","..",
                       "data","bcr","bcr.net"))
```

That works on my laptop, but some reason not on the benchmarking server.

**Comment by isaacsas** [comment]
`normpath`?

https://docs.julialang.org/en/v1/base/file/#Base.Filesystem.normpath
